apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollingupdate
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
  project: default
  source:
    repoURL: git@github.com:SreeVeerDevOps/k8sb20-argocd.git
    targetRevision: HEAD
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: default

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: votingapp
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
  project: default
  source:
    repoURL: git@github.com:SreeVeerDevOps/k8sb20-argocd.git
    targetRevision: HEAD
    path: votingapp
  destination:
    server: https://kubernetes.default.svc
    namespace: votingapp

#The above manifest can be deployed using echo '' | ku apply -f -